In [1]:
import tensorflow as tf
import numpy as np


In [ ]:
data = np.arange(0,100)

In [ ]:
ds1 = tf.keras.utils.timeseries_dataset_from_array(data=data, targets=None, sequence_length=10, sequence_stride=10, batch_size=None)

In [ ]:
for item in ds1:
  print(f"{item} {item.shape}")
  print("*"*50)

[0 1 2 3 4 5 6 7 8 9] (10,)
**************************************************
[10 11 12 13 14 15 16 17 18 19] (10,)
**************************************************
[20 21 22 23 24 25 26 27 28 29] (10,)
**************************************************
[30 31 32 33 34 35 36 37 38 39] (10,)
**************************************************
[40 41 42 43 44 45 46 47 48 49] (10,)
**************************************************
[50 51 52 53 54 55 56 57 58 59] (10,)
**************************************************
[60 61 62 63 64 65 66 67 68 69] (10,)
**************************************************
[70 71 72 73 74 75 76 77 78 79] (10,)
**************************************************
[80 81 82 83 84 85 86 87 88 89] (10,)
**************************************************
[90 91 92 93 94 95 96 97 98 99] (10,)
**************************************************


In [ ]:
ds1_window = tf.data.Dataset.range(100).window(
10
).flat_map(lambda ds : ds.batch(10))

In [ ]:
for item in ds1_window:
  print(f"{item}")
  print("*"*50)

[0 1 2 3 4 5 6 7 8 9]
**************************************************
[10 11 12 13 14 15 16 17 18 19]
**************************************************
[20 21 22 23 24 25 26 27 28 29]
**************************************************
[30 31 32 33 34 35 36 37 38 39]
**************************************************
[40 41 42 43 44 45 46 47 48 49]
**************************************************
[50 51 52 53 54 55 56 57 58 59]
**************************************************
[60 61 62 63 64 65 66 67 68 69]
**************************************************
[70 71 72 73 74 75 76 77 78 79]
**************************************************
[80 81 82 83 84 85 86 87 88 89]
**************************************************
[90 91 92 93 94 95 96 97 98 99]
**************************************************


In [ ]:
ds2 = tf.keras.utils.timeseries_dataset_from_array(data=data, targets=None, sequence_length=10, sequence_stride=10, batch_size=3)

In [ ]:
for item in ds2:
  print(f"{item} {item.shape}")
  print("*"*50)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] (3, 10)
**************************************************
[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]] (3, 10)
**************************************************
[[60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]] (3, 10)
**************************************************
[[90 91 92 93 94 95 96 97 98 99]] (1, 10)
**************************************************


In [ ]:
ds3 = tf.keras.utils.timeseries_dataset_from_array(data=data, targets=None, sequence_length=10, sequence_stride=5, batch_size=3)

In [ ]:
for item in ds3:
  print(f"{item} {item.shape}")
  print("*"*50)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]] (3, 10)
**************************************************
[[15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]
 [25 26 27 28 29 30 31 32 33 34]] (3, 10)
**************************************************
[[30 31 32 33 34 35 36 37 38 39]
 [35 36 37 38 39 40 41 42 43 44]
 [40 41 42 43 44 45 46 47 48 49]] (3, 10)
**************************************************
[[45 46 47 48 49 50 51 52 53 54]
 [50 51 52 53 54 55 56 57 58 59]
 [55 56 57 58 59 60 61 62 63 64]] (3, 10)
**************************************************
[[60 61 62 63 64 65 66 67 68 69]
 [65 66 67 68 69 70 71 72 73 74]
 [70 71 72 73 74 75 76 77 78 79]] (3, 10)
**************************************************
[[75 76 77 78 79 80 81 82 83 84]
 [80 81 82 83 84 85 86 87 88 89]
 [85 86 87 88 89 90 91 92 93 94]] (3, 10)
**************************************************
[[90 91 92 93 94 95 96 97 98 99]] (1, 10)
****

In [ ]:
ds4 = tf.keras.utils.timeseries_dataset_from_array(data=data, targets=data[10:], sequence_length=10, sequence_stride=5, batch_size=None)

In [ ]:
for item, label in ds4:
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[0 1 2 3 4 5 6 7 8 9] maps to 10 and has shape (10,)
**************************************************
[ 5  6  7  8  9 10 11 12 13 14] maps to 15 and has shape (10,)
**************************************************
[10 11 12 13 14 15 16 17 18 19] maps to 20 and has shape (10,)
**************************************************
[15 16 17 18 19 20 21 22 23 24] maps to 25 and has shape (10,)
**************************************************
[20 21 22 23 24 25 26 27 28 29] maps to 30 and has shape (10,)
**************************************************
[25 26 27 28 29 30 31 32 33 34] maps to 35 and has shape (10,)
**************************************************
[30 31 32 33 34 35 36 37 38 39] maps to 40 and has shape (10,)
**************************************************
[35 36 37 38 39 40 41 42 43 44] maps to 45 and has shape (10,)
**************************************************
[40 41 42 43 44 45 46 47 48 49] maps to 50 and has shape (10,)
***********************************

In [ ]:
ds5_window = tf.data.Dataset.range(100).window(
7, shift=1, drop_remainder=True
).flat_map(lambda ds : ds.batch(7))

In [ ]:
ds5_window = ds5_window.map(lambda window : (window[:5], window[-2:]))

In [ ]:
for item, label in ds5_window:
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[0 1 2 3 4] maps to [5 6] and has shape (5,)
**************************************************
[1 2 3 4 5] maps to [6 7] and has shape (5,)
**************************************************
[2 3 4 5 6] maps to [7 8] and has shape (5,)
**************************************************
[3 4 5 6 7] maps to [8 9] and has shape (5,)
**************************************************
[4 5 6 7 8] maps to [ 9 10] and has shape (5,)
**************************************************
[5 6 7 8 9] maps to [10 11] and has shape (5,)
**************************************************
[ 6  7  8  9 10] maps to [11 12] and has shape (5,)
**************************************************
[ 7  8  9 10 11] maps to [12 13] and has shape (5,)
**************************************************
[ 8  9 10 11 12] maps to [13 14] and has shape (5,)
**************************************************
[ 9 10 11 12 13] maps to [14 15] and has shape (5,)
**************************************************
[10 11 1

In [ ]:
ds6_window = tf.data.Dataset.range(100).window(
7, shift=1, drop_remainder=True
).flat_map(lambda ds : ds.batch(7)).map(lambda window : (window[:5], window[-2:])).shuffle(buffer_size=10000, seed=42).batch(10)

In [ ]:
for item, label in ds6_window:
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[[15 16 17 18 19]
 [72 73 74 75 76]
 [10 11 12 13 14]
 [67 68 69 70 71]
 [ 3  4  5  6  7]
 [56 57 58 59 60]
 [46 47 48 49 50]
 [77 78 79 80 81]
 [76 77 78 79 80]
 [49 50 51 52 53]] maps to [[20 21]
 [77 78]
 [15 16]
 [72 73]
 [ 8  9]
 [61 62]
 [51 52]
 [82 83]
 [81 82]
 [54 55]] and has shape (10, 5)
**************************************************
[[54 55 56 57 58]
 [63 64 65 66 67]
 [19 20 21 22 23]
 [ 5  6  7  8  9]
 [12 13 14 15 16]
 [33 34 35 36 37]
 [71 72 73 74 75]
 [87 88 89 90 91]
 [14 15 16 17 18]
 [48 49 50 51 52]] maps to [[59 60]
 [68 69]
 [24 25]
 [10 11]
 [17 18]
 [38 39]
 [76 77]
 [92 93]
 [19 20]
 [53 54]] and has shape (10, 5)
**************************************************
[[20 21 22 23 24]
 [89 90 91 92 93]
 [42 43 44 45 46]
 [17 18 19 20 21]
 [32 33 34 35 36]
 [58 59 60 61 62]
 [68 69 70 71 72]
 [59 60 61 62 63]
 [93 94 95 96 97]
 [91 92 93 94 95]] maps to [[25 26]
 [94 95]
 [47 48]
 [22 23]
 [37 38]
 [63 64]
 [73 74]
 [64 65]
 [98 99]
 [96 97]] and has shape 

In [ ]:
ds7_window = tf.data.Dataset.range(100).window(
2, shift=1, drop_remainder=True
).flat_map(lambda ds : ds.batch(2)).window(5, shift=1, drop_remainder=True).flat_map(lambda ds : ds.batch(5)).map(lambda window : (window[:,0], window[:,-1]))



Cause: could not parse the source code of <function <lambda> at 0x7f50743e3c70>: found multiple definitions with identical signatures at the location. This error may be avoided by defining each lambda on a single line and with unique argument names. The matching definitions were:
Match 0:
lambda ds: ds.batch(5)

Match 1:
lambda ds: ds.batch(2)

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Cause: could not parse the source code of <function <lambda> at 0x7f50743e3c70>: found multiple definitions with identical signatures at the location. This error may be avoided by defining each lambda on a single line and with unique argument names. The matching definitions were:
Match 0:
lambda ds: ds.batch(5)

Match 1:
lambda ds: ds.batch(2)

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


In [ ]:
for item, label in ds7_window:
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[0 1 2 3 4] maps to [1 2 3 4 5] and has shape (5,)
**************************************************
[1 2 3 4 5] maps to [2 3 4 5 6] and has shape (5,)
**************************************************
[2 3 4 5 6] maps to [3 4 5 6 7] and has shape (5,)
**************************************************
[3 4 5 6 7] maps to [4 5 6 7 8] and has shape (5,)
**************************************************
[4 5 6 7 8] maps to [5 6 7 8 9] and has shape (5,)
**************************************************
[5 6 7 8 9] maps to [ 6  7  8  9 10] and has shape (5,)
**************************************************
[ 6  7  8  9 10] maps to [ 7  8  9 10 11] and has shape (5,)
**************************************************
[ 7  8  9 10 11] maps to [ 8  9 10 11 12] and has shape (5,)
**************************************************
[ 8  9 10 11 12] maps to [ 9 10 11 12 13] and has shape (5,)
**************************************************
[ 9 10 11 12 13] maps to [10 11 12 13 14] and h

In [ ]:
ds8_windows = tf.data.Dataset.range(100).window(
1 + 3, shift=1, drop_remainder=True
).flat_map(lambda ds : ds.batch(1 + 3)).window(5, shift=1, drop_remainder=True).flat_map(lambda ds : ds.batch(5)).map(lambda window : (window[:,0], window[:,1:]))

Cause: could not parse the source code of <function <lambda> at 0x7f507446a3b0>: found multiple definitions with identical signatures at the location. This error may be avoided by defining each lambda on a single line and with unique argument names. The matching definitions were:
Match 0:
lambda ds: ds.batch(5)

Match 1:
lambda ds: ds.batch(1 + 3)

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Cause: could not parse the source code of <function <lambda> at 0x7f507446a3b0>: found multiple definitions with identical signatures at the location. This error may be avoided by defining each lambda on a single line and with unique argument names. The matching definitions were:
Match 0:
lambda ds: ds.batch(5)

Match 1:
lambda ds: ds.batch(1 + 3)

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


In [ ]:
for item, label in ds8_windows:
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[0 1 2 3 4] maps to [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]] and has shape (5,)
**************************************************
[1 2 3 4 5] maps to [[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]] and has shape (5,)
**************************************************
[2 3 4 5 6] maps to [[3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]] and has shape (5,)
**************************************************
[3 4 5 6 7] maps to [[ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]] and has shape (5,)
**************************************************
[4 5 6 7 8] maps to [[ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]] and has shape (5,)
**************************************************
[5 6 7 8 9] maps to [[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]] and has shape (5,)
**************************************************
[ 6  7  8  9 10] maps to [[ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]] and has shape (5,)
**********************************

#OEF2

In [8]:
import shutil
import pandas as pd
import numpy as np

In [9]:
file_path = tf.keras.utils.get_file(origin="https://s3.amazonaws.com/keras-datasets/jena_climate_2009_2016.csv.zip", cache_dir="." )

13565642/13565642 [==============================] - 1s 0us/step


In [10]:
shutil.unpack_archive(file_path, "./datasets/jena_climate_2009_2016.csv")

In [11]:
df = pd.read_csv("./datasets/jena_climate_2009_2016.csv/jena_climate_2009_2016.csv")

In [12]:
df.head()

Date Time  p (mbar)  T (degC)  Tpot (K)  Tdew (degC)  rh (%)  \
0  01.01.2009 00:10:00    996.52     -8.02    265.40        -8.90    93.3   
1  01.01.2009 00:20:00    996.57     -8.41    265.01        -9.28    93.4   
2  01.01.2009 00:30:00    996.53     -8.51    264.91        -9.31    93.9   
3  01.01.2009 00:40:00    996.51     -8.31    265.12        -9.07    94.2   
4  01.01.2009 00:50:00    996.51     -8.27    265.15        -9.04    94.1   

   VPmax (mbar)  VPact (mbar)  VPdef (mbar)  sh (g/kg)  H2OC (mmol/mol)  \
0          3.33          3.11          0.22       1.94             3.12   
1          3.23          3.02          0.21       1.89             3.03   
2          3.21          3.01          0.20       1.88             3.02   
3          3.26          3.07          0.19       1.92             3.08   
4          3.27          3.08          0.19       1.92             3.09   

   rho (g/m**3)  wv (m/s)  max. wv (m/s)  wd (deg)  
0       1307.75      1.03           1.75     152.3  
1       1309.80      0.72           1.50     136.1  
2       1310.24      0.19           0.63     171.6  
3       1309.19      0.34           0.50     198.0  
4       1309.00      0.32           0.63     214.3

In [13]:
temperature = df['T (degC)'].values
raw_data = df.drop(['Date Time'], axis=1).values

In [ ]:
raw_data[:3]

array([[ 9.96520e+02, -8.02000e+00,  2.65400e+02, -8.90000e+00,
         9.33000e+01,  3.33000e+00,  3.11000e+00,  2.20000e-01,
         1.94000e+00,  3.12000e+00,  1.30775e+03,  1.03000e+00,
         1.75000e+00,  1.52300e+02],
       [ 9.96570e+02, -8.41000e+00,  2.65010e+02, -9.28000e+00,
         9.34000e+01,  3.23000e+00,  3.02000e+00,  2.10000e-01,
         1.89000e+00,  3.03000e+00,  1.30980e+03,  7.20000e-01,
         1.50000e+00,  1.36100e+02],
       [ 9.96530e+02, -8.51000e+00,  2.64910e+02, -9.31000e+00,
         9.39000e+01,  3.21000e+00,  3.01000e+00,  2.00000e-01,
         1.88000e+00,  3.02000e+00,  1.31024e+03,  1.90000e-01,
         6.30000e-01,  1.71600e+02]])

In [ ]:
raw_data.shape

(420451, 14)

In [14]:
num_train_samples = raw_data.shape[0] // 2
num_val_samples = raw_data.shape[0] // 4

In [15]:
mean = raw_data[:num_train_samples].mean(axis=0)
std = raw_data[:num_train_samples].std(axis=0)

In [16]:
raw_data = (raw_data - mean) /std

In [17]:
raw_data[:num_train_samples].std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
def create_ds(raw_data, target, shuffle=True, batch_size=256):

  delay = 120 * 6 + (24 -1) * 6
  return tf.keras.utils.timeseries_dataset_from_array(
      data=raw_data,
      targets=target[delay:],
      sequence_length=120,
      sampling_rate=6,
      batch_size=batch_size,
      shuffle=shuffle
  )

In [19]:
my_check_ds = create_ds(
  raw_data=df.values[:1000,0],
  target=df.values[:1000,0],
  shuffle=False,
  batch_size=1
)
for features, target in my_check_ds.take(2):
  print(f"{features} maps to {target}")
  print("*"*50)

[[b'01.01.2009 00:10:00' b'01.01.2009 01:10:00' b'01.01.2009 02:10:00'
  b'01.01.2009 03:10:00' b'01.01.2009 04:10:00' b'01.01.2009 05:10:00'
  b'01.01.2009 06:10:00' b'01.01.2009 07:10:00' b'01.01.2009 08:10:00'
  b'01.01.2009 09:10:00' b'01.01.2009 10:10:00' b'01.01.2009 11:10:00'
  b'01.01.2009 12:10:00' b'01.01.2009 13:10:00' b'01.01.2009 14:10:00'
  b'01.01.2009 15:10:00' b'01.01.2009 16:10:00' b'01.01.2009 17:10:00'
  b'01.01.2009 18:10:00' b'01.01.2009 19:10:00' b'01.01.2009 20:10:00'
  b'01.01.2009 21:10:00' b'01.01.2009 22:10:00' b'01.01.2009 23:10:00'
  b'02.01.2009 00:10:00' b'02.01.2009 01:10:00' b'02.01.2009 02:10:00'
  b'02.01.2009 03:10:00' b'02.01.2009 04:10:00' b'02.01.2009 05:10:00'
  b'02.01.2009 06:10:00' b'02.01.2009 07:10:00' b'02.01.2009 08:10:00'
  b'02.01.2009 09:10:00' b'02.01.2009 10:10:00' b'02.01.2009 11:10:00'
  b'02.01.2009 12:10:00' b'02.01.2009 13:10:00' b'02.01.2009 14:10:00'
  b'02.01.2009 15:10:00' b'02.01.2009 16:10:00' b'02.01.2009 17:10:00'
  b'02

In [20]:
train_ds = create_ds(
    raw_data[:num_train_samples],
    temperature[:num_train_samples],
    shuffle=True
)

In [21]:
val_ds = create_ds(
    raw_data[num_train_samples:num_train_samples+num_val_samples],
    temperature[num_train_samples:num_train_samples+num_val_samples],
    shuffle=False
)

In [22]:
test_ds = create_ds(
    raw_data[num_train_samples+num_val_samples:],
    temperature[num_train_samples+num_val_samples:],
    shuffle=False
)

In [ ]:
for samples, targets in train_ds.take(1):
  print(samples.shape)
  print(targets.shape)

(256, 120, 14)
(256,)


In [ ]:
def compute_naive_mae(dataset):
  mean = temperature[:num_train_samples].mean()
  std = temperature[:num_train_samples].std()

  total_error = 0.0
  total_samples = 0
  for samples, target in dataset:
    current_temperature = samples[:, -1, 1] * std + mean
    total_error += np.sum(np.abs(current_temperature - target))
    total_samples += samples.shape[0]

  return total_error / total_samples

In [ ]:
compute_naive_mae(val_ds)

2.4404981103842553

In [ ]:
compute_naive_mae(test_ds)

2.621035911602208

In [23]:
train_ds = train_ds.cache().prefetch(1)
val_ds = val_ds.cache().prefetch(1)

In [ ]:
def get_model():
  model = tf.keras.Sequential()
  model.add(tf.keras.layers.Flatten(input_shape=(120, 14)))
  model.add(tf.keras.layers.Dense(16, activation='relu', ))
  model.add(tf.keras.layers.Dense(1, activation=None))

  return model

In [ ]:
model = get_model()

In [ ]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 1680)              0         
                                                                 
 dense_8 (Dense)             (None, 16)                26896     
                                                                 
 dense_9 (Dense)             (None, 1)                 17        
                                                                 
Total params: 26913 (105.13 KB)
Trainable params: 26913 (105.13 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile(loss='mse',
optimizer='rmsprop',
metrics=["mae"])

In [ ]:
checkpont_cb = tf.keras.callbacks.ModelCheckpoint(
    filepath='jena_dense.keras',
    save_best_only=True
)

In [ ]:
model.fit(train_ds, epochs=10, callbacks=[checkpont_cb],
 validation_data=val_ds)

Epoch 1/10
818/818 [==============================] - 34s 41ms/step - loss: 13.5994 - mae: 2.8486 - val_loss: 11.1205 - val_mae: 2.6335
Epoch 2/10
818/818 [==============================] - 5s 6ms/step - loss: 9.5147 - mae: 2.4274 - val_loss: 10.7188 - val_mae: 2.5883
Epoch 3/10
818/818 [==============================] - 4s 5ms/step - loss: 8.7559 - mae: 2.3267 - val_loss: 10.9703 - val_mae: 2.6246
Epoch 4/10
818/818 [==============================] - 4s 5ms/step - loss: 8.2364 - mae: 2.2561 - val_loss: 10.1947 - val_mae: 2.5209
Epoch 5/10
818/818 [==============================] - 4s 5ms/step - loss: 7.8808 - mae: 2.2059 - val_loss: 10.2047 - val_mae: 2.5209
Epoch 6/10
818/818 [==============================] - 4s 5ms/step - loss: 7.5929 - mae: 2.1648 - val_loss: 10.2698 - val_mae: 2.5269
Epoch 7/10
818/818 [==============================] - 4s 5ms/step - loss: 7.3701 - mae: 2.1331 - val_loss: 10.3287 - val_mae: 2.5336
Epoch 8/10
818/818 [==============================] - 4s 5ms/step 

In [ ]:
model.evaluate(val_ds)

408/408 [==============================] - 1s 3ms/step - loss: 10.6096 - mae: 2.5671


[10.609573364257812, 2.5670697689056396]

In [ ]:
model = tf.keras.models.load_model('jena_dense.keras')

In [ ]:
model.evaluate(val_ds)

408/408 [==============================] - 1s 3ms/step - loss: 10.1947 - mae: 2.5209


[10.194686889648438, 2.5209014415740967]

In [ ]:
model.evaluate(test_ds)

408/408 [==============================] - 10s 24ms/step - loss: 11.0779 - mae: 2.6318


[11.07787036895752, 2.6317505836486816]

In [ ]:
def get_model():
  model = tf.keras.Sequential()
  model.add(tf.keras.layers.SimpleRNN(16, input_shape=(None, 14)))
  model.add(tf.keras.layers.Dense(1, activation=None))

  return model

In [ ]:
model_RNN = get_model()

In [ ]:
model_RNN.compile(loss='mse',
optimizer='rmsprop',
metrics=["mae"])

In [ ]:
checkpont_cb = tf.keras.callbacks.ModelCheckpoint(
    filepath='jena_RNN.keras',
    save_best_only=True
)

In [ ]:
model_RNN.fit(train_ds, epochs=10, callbacks=[checkpont_cb],
 validation_data=val_ds)

Epoch 1/10
818/818 [==============================] - 24s 28ms/step - loss: 49.7177 - mae: 5.2324 - val_loss: 14.3381 - val_mae: 2.8011
Epoch 2/10
818/818 [==============================] - 23s 28ms/step - loss: 11.7285 - mae: 2.6462 - val_loss: 9.2156 - val_mae: 2.3494
Epoch 3/10
818/818 [==============================] - 22s 27ms/step - loss: 10.5340 - mae: 2.5289 - val_loss: 9.0144 - val_mae: 2.3292
Epoch 4/10
818/818 [==============================] - 23s 28ms/step - loss: 10.3155 - mae: 2.5026 - val_loss: 8.9777 - val_mae: 2.3277
Epoch 5/10
818/818 [==============================] - 23s 28ms/step - loss: 10.2143 - mae: 2.4898 - val_loss: 8.9488 - val_mae: 2.3249
Epoch 6/10
818/818 [==============================] - 22s 27ms/step - loss: 10.1403 - mae: 2.4806 - val_loss: 8.9309 - val_mae: 2.3228
Epoch 7/10
818/818 [==============================] - 23s 28ms/step - loss: 10.0450 - mae: 2.4685 - val_loss: 8.9188 - val_mae: 2.3232
Epoch 8/10
818/818 [==============================] - 

In [ ]:
model_RNN.evaluate(val_ds)

408/408 [==============================] - 5s 11ms/step - loss: 8.9819 - mae: 2.3325


[8.981934547424316, 2.3324761390686035]

In [ ]:
model_RNN = tf.keras.models.load_model('jena_RNN.keras')

In [ ]:
model_RNN.evaluate(val_ds)

408/408 [==============================] - 5s 11ms/step - loss: 8.9188 - mae: 2.3232


[8.9187593460083, 2.323153257369995]

In [ ]:
def get_model():
  model = tf.keras.Sequential()
  model.add(tf.keras.layers.RNN(tf.keras.layers.LSTMCell(16), input_shape=(None, 14)))
  model.add(tf.keras.layers.Dense(1, activation=None))

  return model

In [ ]:
model_lstm = get_model()

In [ ]:
model_lstm.compile(loss='mse',
optimizer='rmsprop',
metrics=["mae"])

In [ ]:
checkpont_cb = tf.keras.callbacks.ModelCheckpoint(
    filepath='jena_lstm.keras',
    save_best_only=True
)

In [ ]:
model_lstm.fit(train_ds, epochs=10, callbacks=[checkpont_cb],
 validation_data=val_ds)

Epoch 1/10
818/818 [==============================] - 57s 68ms/step - loss: 43.0464 - mae: 4.8110 - val_loss: 12.9088 - val_mae: 2.7346
Epoch 2/10
818/818 [==============================] - 55s 67ms/step - loss: 11.2003 - mae: 2.5991 - val_loss: 10.0936 - val_mae: 2.4526
Epoch 3/10
818/818 [==============================] - 55s 67ms/step - loss: 9.7415 - mae: 2.4428 - val_loss: 9.9169 - val_mae: 2.4279
Epoch 4/10
818/818 [==============================] - 55s 68ms/step - loss: 9.2766 - mae: 2.3817 - val_loss: 9.8789 - val_mae: 2.4259
Epoch 5/10
818/818 [==============================] - 56s 68ms/step - loss: 8.9160 - mae: 2.3321 - val_loss: 10.0279 - val_mae: 2.4420
Epoch 6/10
818/818 [==============================] - 56s 68ms/step - loss: 8.5611 - mae: 2.2861 - val_loss: 9.9387 - val_mae: 2.4348
Epoch 7/10
818/818 [==============================] - 55s 68ms/step - loss: 8.2713 - mae: 2.2493 - val_loss: 10.2428 - val_mae: 2.4806
Epoch 8/10
818/818 [==============================] - 56

In [ ]:
model_lstm.evaluate(val_ds)

408/408 [==============================] - 11s 26ms/step - loss: 10.5908 - mae: 2.5287


[10.59077262878418, 2.528679132461548]

In [ ]:
model_lstm = tf.keras.models.load_model('jena_lstm.keras')

In [ ]:
model_lstm.evaluate(val_ds)

408/408 [==============================] - 11s 26ms/step - loss: 9.8789 - mae: 2.4259


[9.878949165344238, 2.4259285926818848]

In [2]:
def get_model():
  model = tf.keras.Sequential()
  model.add(tf.keras.layers.LSTM(32, recurrent_dropout=0.25, input_shape=(None, 14)))
  model.add(tf.keras.layers.Dropout(0.50))
  model.add(tf.keras.layers.Dense(1, activation=None))

  return model

In [3]:
model_lstm_dropout = get_model()

In [5]:
model_lstm_dropout.compile(loss='mse',
optimizer='rmsprop',
metrics=["mae"])

In [6]:
checkpont_cb = tf.keras.callbacks.ModelCheckpoint(
    filepath='jena_lstm_dropout.keras',
    save_best_only=True
)

In [24]:
model_lstm_dropout.fit(train_ds, epochs=10, callbacks=[checkpont_cb],
 validation_data=val_ds)

Epoch 1/10
818/818 [==============================] - 123s 145ms/step - loss: 29.9594 - mae: 4.0191 - val_loss: 9.9568 - val_mae: 2.4402
Epoch 2/10
818/818 [==============================] - 99s 121ms/step - loss: 15.0661 - mae: 3.0152 - val_loss: 9.7708 - val_mae: 2.4240
Epoch 3/10
818/818 [==============================] - 99s 122ms/step - loss: 14.2917 - mae: 2.9316 - val_loss: 9.8867 - val_mae: 2.4348
Epoch 4/10
818/818 [==============================] - 108s 132ms/step - loss: 13.7363 - mae: 2.8726 - val_loss: 9.6002 - val_mae: 2.3888
Epoch 5/10
818/818 [==============================] - 98s 120ms/step - loss: 13.2476 - mae: 2.8214 - val_loss: 9.4482 - val_mae: 2.3733
Epoch 6/10
818/818 [==============================] - 98s 120ms/step - loss: 12.8399 - mae: 2.7778 - val_loss: 9.4002 - val_mae: 2.3643
Epoch 7/10
818/818 [==============================] - 99s 121ms/step - loss: 12.4327 - mae: 2.7322 - val_loss: 9.0699 - val_mae: 2.3283
Epoch 8/10
818/818 [==========================

In [25]:
model_lstm_dropout.evaluate(val_ds)

408/408 [==============================] - 11s 28ms/step - loss: 9.2970 - mae: 2.3560


[9.297019958496094, 2.3560290336608887]

In [26]:
model_lstm = tf.keras.models.load_model('jena_lstm_dropout.keras')

In [27]:
model_lstm.evaluate(val_ds)

408/408 [==============================] - 12s 28ms/step - loss: 9.0699 - mae: 2.3283


[9.069863319396973, 2.328277826309204]

#OEF3

In [37]:
class MyLSTMCell(tf.keras.layers.Layer):
  def __init__(self, units, **kwargs):
    super().__init__(**kwargs)
    self.state_size = [units, units]
    self.output_size = units

    self.dense_i = tf.keras.layers.Dense(
        units=units,
        bias_initializer="zeros",
        activation="sigmoid")

    self.dense_f = tf.keras.layers.Dense(
        units=units,
        bias_initializer="ones",
        activation="sigmoid"
    )

    self.dense_g = tf.keras.layers.Dense(
        units=units,
        bias_initializer="zeros",
        activation="tanh"
    )

    self.dense_o = tf.keras.layers.Dense(
        units=units,
        bias_initializer="zeros",
        activation="sigmoid"
    )

  def call(self, inputs, states):
    previous_short_term_state = states[0]
    previous_long_term_state = states[1]

    input_and_previous_short_term = tf.concat([inputs,previous_short_term_state], axis=-1)

    i = self.dense_i(input_and_previous_short_term)
    f = self.dense_f(input_and_previous_short_term)
    g = self.dense_g(input_and_previous_short_term)
    o = self.dense_o(input_and_previous_short_term)

    new_carry_state = f * previous_short_term_state + i * g
    y = o * tf.keras.activations.tanh(new_carry_state)

    return y, [y, new_carry_state]


In [38]:
BATCH_SIZE = 5
NUM_STEPS = 10
NUM_FEATURES = 3
UNITS=4
inputs = tf.random.normal([BATCH_SIZE, NUM_STEPS, NUM_FEATURES])

In [39]:
lstm = MyLSTMCell(units=UNITS)

model = tf.keras.Sequential([
    tf.keras.layers.RNN(lstm)
])

In [40]:
output = model(inputs)

In [41]:
output

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.1670021 , -0.05199262, -0.06833372,  0.07145083],
       [ 0.11256775, -0.22498573,  0.06954963,  0.01445085],
       [-0.31895334,  0.02570039,  0.06424004, -0.217943  ],
       [-0.09113282, -0.17962831, -0.1074129 , -0.10757056],
       [-0.26009306, -0.12936014,  0.0550205 , -0.19001305]],
      dtype=float32)>

In [42]:
lstmCell = tf.keras.layers.LSTMCell(UNITS)

rnn = tf.keras.layers.RNN(lstmCell)

In [43]:
output = rnn(inputs)

In [44]:
output

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.10922996,  0.07909946,  0.18653241, -0.03802745],
       [-0.01498318, -0.20974657,  0.04806787, -0.11321456],
       [-0.5844209 , -0.34397346, -0.12141539,  0.03654138],
       [-0.00075903,  0.0856434 ,  0.09951016,  0.02034503],
       [-0.3186249 , -0.05421087, -0.01006479,  0.07768526]],
      dtype=float32)>